#ifndef _INC_REACTOS_BUILDNO				
#define _INC_REACTOS_BUILDNO				
#define KERNEL_VERSION_BUILD	20110530		
#define KERNEL_VERSION_BUILD_HEX	0x0			
#define KERNEL_VERSION_BUILD_STR	"20110530"		
#define KERNEL_VERSION_BUILD_RC	"20110530\0"	
#define KERNEL_RELEASE_RC	"0.0.1\0"	
#define KERNEL_RELEASE_STR	"0.0.1"	
#define KERNEL_VERSION_RC	"0.0.1\0"	
#define KERNEL_VERSION_STR	"0.0.1"	
#define REACTOS_DLL_VERSION_MAJOR 0	
#define REACTOS_DLL_RELEASE_RC	"0.0.1\0"	
#define REACTOS_DLL_RELEASE_STR	"0.0.1"	
#define REACTOS_DLL_VERSION_RC	"0.0.1\0"	
#define REACTOS_DLL_VERSION_STR	"0.0.1"	
#define REACTOS_DLL_VERSION_STR	"0.0.1"	
#endif	
