#include "mem\global.c"
#include "mem\isbad.c"
#include "mem\procmem.c"
#include "mem\resnotify.c"
#include "mem\section.c"
#include "mem\virtual.c"
#include "mem\local.c"
#include "mem\heap.c"